
trigger:
- master

pool:
  vmImage: ubuntu-latest

stages: 
- stage: Build
  jobs:
  - job: FirstJob
    steps:
      - bash: echo Build FirstJob
  - job: SecondJob
    steps:
      - -bas: echo Build SecondJob
- stage: DevDeploy
  jobs:
  - job: Devdeployjob
    steps:
      - bash: echo Build dvdeployjob
- stage: QADeploy
  jobs:
  - job: QAdeploy
    steps:
      - bash: echo Build QAdeployjob
- stage: ProdDeploy
  jobs:
  - job: proddeploy
    steps:
      - bash: echo Build proddeployjob
steps:
- script: echo JOb1 Step1!
  displayName: 'Run a one-line script'

